add local license checks
ionworks/Ionwizard pull request #8
Opened 2024-10-24 21:06 UTC by valentinsulzer

- function to save the config to the user config dir from platformdirs
- functions to load the config and check the license

2024-10-28 23:46 UTC, kratman requested changes
I put the changes up in another branch

2024-10-28 23:46 UTC, kratman commented on ionwizard/validate.py
> +from .library_wizard import KEYGEN_ACCOUNT_ID
Actually I fixed this a different way in my review PR

2024-10-28 23:46 UTC, kratman commented on ionwizard/validate.py
> +def library(library_name, custom_library_key=None):
PyCharm flags the scope shadowing in the for loop
![image](https://github.com/user-attachments/assets/71a8edae-f03f-4261-92f4-e3aca27654b4)

2024-10-28 23:46 UTC, kratman commented on ionwizard/library_wizard.py
> +        # IonWorksPipWizard.install_from(processed_config)
I think if we want a script to just save the config, then we can make one for that, but this should still install packages if needed.

2024-10-29 00:59 UTC, valentinsulzer commented on ionwizard/validate.py
> +def library(library_name, custom_library_key=None):
the idea was to call it as `ionwizard.validate.library` (in which case the action is "validate library") but I'm not too fussed about this

2024-10-29 14:22 UTC, merged